# -*- coding: utf-8 -*-
"""deep LPR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hC146-Q4kA7K-8tlQaMA2M-sUE7pc_2V
"""

from google.colab import drive
drive.mount('/content/drive')

import cv2
import numpy as np
from skimage import morphology

image = cv2.imread('/content/drive/My Drive/CAR1/11.JPG',cv2.IMREAD_COLOR)

from google.colab.patches import cv2_imshow

#image = cv2.resize(image,(384,192))

cv2_imshow(image)

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

cv2_imshow(gray)

median = cv2.medianBlur(gray, 3)

cv2_imshow(median)

equ = cv2.equalizeHist(median)

cv2_imshow(equ)

sobely = cv2.Sobel(imgf,cv2.CV_64F,0,1,ksize=3)

cv2_imshow(sobely)

blur = cv2.blur(sobely,(3,3))

cv2_imshow(blur)

import numpy as np
import cv2
kernel = morphology.cube(1)

opening = cv2.morphologyEx(blur,cv2.MORPH_OPEN, kernel)

cv2_imshow(opening)

tophat = cv2.morphologyEx(opening, cv2.MORPH_TOPHAT, kernel)

#blur1 = cv2.GaussianBlur(opening,(3,3),0)
#laplacian = cv2.Laplacian(blur1,cv2.CV_64F)
	
#gray1 = cv2.cvtColor(laplacian, cv2.COLOR_BGR2GRAY)

cv2_imshow(tophat)

ret, thresh1 = cv2.threshold(tophat, 120, 255, cv2.THRESH_BINARY + 
                                            cv2.THRESH_OTSU)  
cv2_imshow(thresh1)

#from skimage.filters import threshold_otsu
#thresh = threshold_otsu(equ)
#binary = image > thresh
#cv2_imshow(binary)